export const toPresent = "to present";

export const eduParity = {
    ["СПО"]: 0,
    ["Бакалавриат"]: 1,
    ["Специалитет"]: 2,
    ["Магистратура"]: 3,
    ["Подготовка кадров ВК"]: 4,
}

export const citizens = [
    {
        id: 0,
        surname: "Добромыслов",
        name: "Алексей",
        patronymic: "Владимирович",
        email: "avd0505@yandex.ru",
        phoneNumber: "+79258479798",
        birthDate: "2002-05-05",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Информатика и вычислительная техника",
                startDate: "2019-09-01",
                endDate: "2023-07-20",
            },
            {
                level: "Магистратура",
                specialization: "Информатика и вычислительная техника",
                startDate: "2023-09-01",
                endDate: "to present",
            }
        ]
    },
    {
        id: 1,
        surname: "Иванов",
        name: "Пётр",
        patronymic: "Александрович",
        email: "",
        phoneNumber: "+79031234567",
        birthDate: "1998-03-15",
        sex: "Мужской",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Экономика",
                startDate: "2016-09-01",
                endDate: "2020-07-10",
            },
            {
                level: "Магистратура",
                specialization: "Финансы и кредит",
                startDate: "2020-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 2,
        surname: "Смирнова",
        name: "Елена",
        patronymic: "Викторовна",
        email: "elena.sm@mail.ru",
        phoneNumber: "",
        birthDate: "2000-10-22",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Педагогика",
                startDate: "2018-09-01",
                endDate: "2022-06-25",
            },
        ],
    },
    {
        id: 3,
        surname: "Кузнецов",
        name: "Дмитрий",
        patronymic: "Сергеевич",
        email: "dkuznetsov@mail.ru",
        phoneNumber: "+79237654321",
        birthDate: "1995-12-05",
        sex: "Мужской",
        educationStatus: "Нет",
        education: [],
    },
    {
        id: 4,
        surname: "Попова",
        name: "Мария",
        patronymic: "Игоревна",
        email: "m.popova@yandex.ru",
        phoneNumber: "",
        birthDate: "1997-07-30",
        sex: "Женский",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Юриспруденция",
                startDate: "2014-09-01",
                endDate: "2020-07-20",
            },
        ],
    },
    {
        id: 5,
        surname: "Васильев",
        name: "Андрей",
        patronymic: "Николаевич",
        email: "",
        phoneNumber: "+79161234567",
        birthDate: "2001-01-17",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Математика",
                startDate: "2018-09-01",
                endDate: "2022-06-25",
            },
        ],
    },
    {
        id: 6,
        surname: "Морозова",
        name: "Анна",
        patronymic: "Дмитриевна",
        email: "morozova_anna@mail.ru",
        phoneNumber: "+79039876543",
        birthDate: "1994-04-10",
        sex: "Женский",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Физика",
                startDate: "2011-09-01",
                endDate: "2015-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Физика",
                startDate: "2015-09-01",
                endDate: "2017-06-30",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Квантовая физика",
                startDate: "2017-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 7,
        surname: "Новиков",
        name: "Илья",
        patronymic: "Валерьевич",
        email: "",
        phoneNumber: "",
        birthDate: "2003-11-11",
        sex: "Мужской",
        educationStatus: "Нет",
        education: [],
    },
    {
        id: 8,
        surname: "Зайцева",
        name: "Ольга",
        patronymic: "Павловна",
        email: "zaitseva_olga@mail.ru",
        phoneNumber: "+79251234567",
        birthDate: "1999-02-25",
        sex: "Женский",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Журналистика",
                startDate: "2016-09-01",
                endDate: "2020-07-15",
            },
            {
                level: "Магистратура",
                specialization: "Медиа и коммуникации",
                startDate: "2020-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 9,
        surname: "Соколов",
        name: "Владимир",
        patronymic: "Иванович",
        email: "v.sokolov@mail.ru",
        phoneNumber: "+79041234567",
        birthDate: "1989-08-01",
        sex: "Мужской",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Медицина",
                startDate: "2007-09-01",
                endDate: "2013-07-20",
            },
        ],
    },
    {
        id: 10,
        surname: "Козлова",
        name: "Екатерина",
        patronymic: "Алексеевна",
        email: "",
        phoneNumber: "",
        birthDate: "2002-06-10",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Психология",
                startDate: "2019-09-01",
                endDate: "2023-06-30",
            },
        ],
    },
    {
        id: 11,
        surname: "Лебедев",
        name: "Максим",
        patronymic: "Олегович",
        email: "m.lebedev@mail.ru",
        phoneNumber: "+79251231234",
        birthDate: "1996-05-14",
        sex: "Мужской",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Информатика",
                startDate: "2014-09-01",
                endDate: "2018-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Прикладная информатика",
                startDate: "2018-09-01",
                endDate: "2020-06-25",
            },
        ],
    },
    {
        id: 12,
        surname: "Куликова",
        name: "Наталья",
        patronymic: "Владимировна",
        email: "",
        phoneNumber: "+79259876543",
        birthDate: "1993-01-29",
        sex: "Женский",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Филология",
                startDate: "2011-09-01",
                endDate: "2015-06-20",
            },
            {
                level: "Магистратура",
                specialization: "Лингвистика",
                startDate: "2015-09-01",
                endDate: "2017-07-01",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Современная филология",
                startDate: "2017-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 13,
        surname: "Павлов",
        name: "Игорь",
        patronymic: "Анатольевич",
        email: "igor.pavlov@mail.ru",
        phoneNumber: "+79034561234",
        birthDate: "2000-12-11",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Право",
                startDate: "2018-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 14,
        surname: "Григорьева",
        name: "Светлана",
        patronymic: "Юрьевна",
        email: "s.grigorieva@mail.ru",
        phoneNumber: "",
        birthDate: "1997-11-03",
        sex: "Женский",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Химия",
                startDate: "2012-09-01",
                endDate: "2018-07-01",
            },
        ],
    },
    {
        id: 15,
        surname: "Михайлов",
        name: "Александр",
        patronymic: "Петрович",
        email: "alex.mih@mail.ru",
        phoneNumber: "+79122334455",
        birthDate: "1995-04-21",
        sex: "Мужской",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Специалитет",
                specialization: "Строительство",
                startDate: "2012-09-01",
                endDate: "2018-06-20",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Градостроительство",
                startDate: "2018-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 16,
        surname: "Федорова",
        name: "Екатерина",
        patronymic: "Сергеевна",
        email: "",
        phoneNumber: "+79098765432",
        birthDate: "2001-09-29",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Журналистика",
                startDate: "2019-09-01",
                endDate: "2023-06-30",
            },
        ],
    },
    {
        id: 17,
        surname: "Никитин",
        name: "Сергей",
        patronymic: "Андреевич",
        email: "sergei.nikitin@mail.ru",
        phoneNumber: "+79259998877",
        birthDate: "1998-12-20",
        sex: "Мужской",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Инженерия",
                startDate: "2016-09-01",
                endDate: "2020-07-10",
            },
            {
                level: "Магистратура",
                specialization: "Энергетика",
                startDate: "2020-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 18,
        surname: "Алексеева",
        name: "Марина",
        patronymic: "Владимировна",
        email: "marina.al@mail.ru",
        phoneNumber: "",
        birthDate: "1994-08-08",
        sex: "Женский",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Специалитет",
                specialization: "Биология",
                startDate: "2010-09-01",
                endDate: "2016-06-25",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Молекулярная биология",
                startDate: "2016-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 19,
        surname: "Петров",
        name: "Николай",
        patronymic: "Александрович",
        email: "",
        phoneNumber: "+79032223344",
        birthDate: "2003-05-12",
        sex: "Мужской",
        educationStatus: "Нет",
        education: [],
    },
    {
        id: 20,
        surname: "Сидорова",
        name: "Татьяна",
        patronymic: "Ильинична",
        email: "t.sidorova@mail.ru",
        phoneNumber: "",
        birthDate: "1999-04-30",
        sex: "Женский",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Маркетинг",
                startDate: "2016-09-01",
                endDate: "2020-06-15",
            },
            {
                level: "Магистратура",
                specialization: "Управление бизнесом",
                startDate: "2020-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 21,
        surname: "Орлов",
        name: "Денис",
        patronymic: "Юрьевич",
        email: "d.orlov@mail.ru",
        phoneNumber: "+79254567890",
        birthDate: "1997-10-19",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Экономика",
                startDate: "2014-09-01",
                endDate: "2018-06-15",
            },
        ],
    },
    {
        id: 22,
        surname: "Мельникова",
        name: "Нина",
        patronymic: "Алексеевна",
        email: "",
        phoneNumber: "+79167654321",
        birthDate: "2000-01-05",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Социология",
                startDate: "2017-09-01",
                endDate: "2021-06-30",
            },
        ],
    },
    {
        id: 23,
        surname: "Жуков",
        name: "Роман",
        patronymic: "Петрович",
        email: "r.jukov@mail.ru",
        phoneNumber: "",
        birthDate: "1995-09-09",
        sex: "Мужской",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Архитектура",
                startDate: "2011-09-01",
                endDate: "2017-06-30",
            },
        ],
    },
    {
        id: 24,
        surname: "Егорова",
        name: "Алина",
        patronymic: "Игоревна",
        email: "alina.egorova@mail.ru",
        phoneNumber: "+79251789999",
        birthDate: "1998-02-28",
        sex: "Женский",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "История",
                startDate: "2016-09-01",
                endDate: "2020-06-30",
            },
            {
                level: "Магистратура",
                specialization: "Культурология",
                startDate: "2020-09-01",
                endDate: "2022-07-01",
            },
        ],
    },
    {
        id: 25,
        surname: "Воронцов",
        name: "Сергей",
        patronymic: "Иванович",
        email: "",
        phoneNumber: "",
        birthDate: "2002-07-13",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Информатика",
                startDate: "2019-09-01",
                endDate: "2023-06-30",
            },
        ],
    },
    {
        id: 26,
        surname: "Маслова",
        name: "Оксана",
        patronymic: "Романовна",
        email: "ok.maslova@mail.ru",
        phoneNumber: "+79123456789",
        birthDate: "1993-11-26",
        sex: "Женский",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Специалитет",
                specialization: "Педагогика",
                startDate: "2010-09-01",
                endDate: "2016-07-01",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Педагогическая психология",
                startDate: "2016-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 27,
        surname: "Гусев",
        name: "Виктор",
        patronymic: "Павлович",
        email: "vgusev@mail.ru",
        phoneNumber: "",
        birthDate: "1999-05-14",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Автоматика",
                startDate: "2016-09-01",
                endDate: "2020-07-01",
            },
        ],
    },
    {
        id: 28,
        surname: "Киселева",
        name: "Ирина",
        patronymic: "Сергеевна",
        email: "",
        phoneNumber: "",
        birthDate: "1995-10-10",
        sex: "Женский",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Экология",
                startDate: "2010-09-01",
                endDate: "2016-06-20",
            },
        ],
    },
    {
        id: 29,
        surname: "Данилов",
        name: "Анатолий",
        patronymic: "Александрович",
        email: "danilov.anat@mail.ru",
        phoneNumber: "+79047654321",
        birthDate: "1997-03-08",
        sex: "Мужской",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Физика",
                startDate: "2014-09-01",
                endDate: "2018-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Прикладная физика",
                startDate: "2018-09-01",
                endDate: "2020-06-30",
            },
        ],
    },
    {
        id: 30,
        surname: "Емельянова",
        name: "Юлия",
        patronymic: "Львовна",
        email: "",
        phoneNumber: "+79258887766",
        birthDate: "2000-12-12",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Журналистика",
                startDate: "2017-09-01",
                endDate: "2021-06-25",
            },
        ],
    },
    {
        id: 31,
        surname: "Исаев",
        name: "Денис",
        patronymic: "Валерьевич",
        email: "isaev.d@mail.ru",
        phoneNumber: "+79168881122",
        birthDate: "1996-01-02",
        sex: "Мужской",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Специалитет",
                specialization: "Менеджмент",
                startDate: "2012-09-01",
                endDate: "2018-06-30",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Стратегический менеджмент",
                startDate: "2018-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 32,
        surname: "Кузьмина",
        name: "Вера",
        patronymic: "Анатольевна",
        email: "vera.k@mail.ru",
        phoneNumber: "",
        birthDate: "1998-07-16",
        sex: "Женский",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Лингвистика",
                startDate: "2016-09-01",
                endDate: "2020-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Перевод и переводоведение",
                startDate: "2020-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 33,
        surname: "Ларин",
        name: "Владислав",
        patronymic: "Константинович",
        email: "",
        phoneNumber: "+79254445566",
        birthDate: "2001-03-03",
        sex: "Мужской",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Прикладная математика",
                startDate: "2019-09-01",
                endDate: "2023-07-01",
            },
        ],
    },
    {
        id: 34,
        surname: "Тихомиров",
        name: "Егор",
        patronymic: "Михайлович",
        email: "egor.t@mail.ru",
        phoneNumber: "",
        birthDate: "1994-06-27",
        sex: "Мужской",
        educationStatus: "Подготовка кадров ВК",
        education: [
            {
                level: "Специалитет",
                specialization: "Юриспруденция",
                startDate: "2012-09-01",
                endDate: "2018-07-01",
            },
            {
                level: "Подготовка кадров ВК",
                specialization: "Государственное и муниципальное управление",
                startDate: "2018-09-01",
                endDate: "to present",
            },
        ],
    },
    {
        id: 35,
        surname: "Чернова",
        name: "Алина",
        patronymic: "Викторовна",
        email: "",
        phoneNumber: "+79031112233",
        birthDate: "2000-08-19",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Экология",
                startDate: "2017-09-01",
                endDate: "2021-06-15",
            },
        ],
    },
    {
        id: 36,
        surname: "Сергейчук",
        name: "Виктория",
        patronymic: "Александровна",
        email: "victoria.serg@mail.ru",
        phoneNumber: "+79253331122",
        birthDate: "1997-05-21",
        sex: "Женский",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Философия",
                startDate: "2014-09-01",
                endDate: "2018-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Логика и методология науки",
                startDate: "2018-09-01",
                endDate: "2020-06-30",
            },
        ],
    },
    {
        id: 37,
        surname: "Романов",
        name: "Артём",
        patronymic: "Владимирович",
        email: "",
        phoneNumber: "",
        birthDate: "2003-02-14",
        sex: "Мужской",
        educationStatus: "Нет",
        education: [],
    },
    {
        id: 38,
        surname: "Мартынова",
        name: "Ольга",
        patronymic: "Юрьевна",
        email: "martynova.o@mail.ru",
        phoneNumber: "+79254447788",
        birthDate: "1996-09-05",
        sex: "Женский",
        educationStatus: "Специалитет",
        education: [
            {
                level: "Специалитет",
                specialization: "Психология",
                startDate: "2012-09-01",
                endDate: "2018-07-01",
            },
        ],
    },
    {
        id: 39,
        surname: "Волков",
        name: "Иван",
        patronymic: "Даниилович",
        email: "i.volkov@mail.ru",
        phoneNumber: "+79041112233",
        birthDate: "1998-04-12",
        sex: "Мужской",
        educationStatus: "Магистратура",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Прикладная математика",
                startDate: "2016-09-01",
                endDate: "2020-07-01",
            },
            {
                level: "Магистратура",
                specialization: "Математическое моделирование",
                startDate: "2020-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 40,
        surname: "Белова",
        name: "Людмила",
        patronymic: "Петровна",
        email: "",
        phoneNumber: "+79253334455",
        birthDate: "2001-11-22",
        sex: "Женский",
        educationStatus: "Бакалавриат",
        education: [
            {
                level: "Бакалавриат",
                specialization: "Педагогика",
                startDate: "2018-09-01",
                endDate: "2022-06-30",
            },
        ],
    },
    {
        id: 41,
        surname: 'Иванов',
        name: 'Петр',
        patronymic: 'Сергеевич',
        email: 'p.ivanov@mail.ru',
        phoneNumber: '+79001234567',
        birthDate: '2000-03-15',
        sex: 'Мужской',
        educationStatus: 'СПО',
        education: [
            {
                level: 'СПО',
                specialization: 'Экономика и бухгалтерский учет',
                startDate: '2017-09-01',
                endDate: '2020-06-30',
            },
        ],
    },
    {
        id: 42,
        surname: 'Петрова',
        name: 'Марина',
        patronymic: 'Александровна',
        email: 'marina.pet@mail.ru',
        phoneNumber: '+79007654321',
        birthDate: '1999-11-22',
        sex: 'Женский',
        educationStatus: 'СПО',
        education: [
            {
                level: 'СПО',
                specialization: 'Дизайн интерьеров',
                startDate: '2016-09-01',
                endDate: '2019-06-30',
            },
        ],
    },
    {
        id: 43,
        surname: 'Сидоров',
        name: 'Александр',
        patronymic: 'Николаевич',
        email: 'a.sidorov@mail.ru',
        phoneNumber: '+79251239876',
        birthDate: '2001-07-07',
        sex: 'Мужской',
        educationStatus: 'СПО',
        education: [
            {
                level: 'СПО',
                specialization: 'Программирование в компьютерных системах',
                startDate: '2018-09-01',
                endDate: '2021-06-30',
            },
        ],
    },
    {
        id: 44,
        surname: 'Кузнецова',
        name: 'Ольга',
        patronymic: 'Владимировна',
        email: 'olga.k@mail.ru',
        phoneNumber: '+79009876543',
        birthDate: '2000-12-12',
        sex: 'Женский',
        educationStatus: 'СПО',
        education: [
            {
                level: 'СПО',
                specialization: 'Туризм и гостиничное дело',
                startDate: '2017-09-01',
                endDate: '2020-06-30',
            },
        ],
    },
    {
        id: 45,
        surname: 'Морозов',
        name: 'Дмитрий',
        patronymic: 'Анатольевич',
        email: 'd.morozov@mail.ru',
        phoneNumber: '+79253456789',
        birthDate: '1998-04-30',
        sex: 'Мужской',
        educationStatus: 'СПО',
        education: [
            {
                level: 'СПО',
                specialization: 'Автомеханик',
                startDate: '2015-09-01',
                endDate: '2018-06-30',
            },
        ],
    },
];


